export { default as Registration } from './Registration/Registration'
export { default as Authorization } from './Authorization/Authorization'
export { default as Forgot } from './Forgot/Forgot'
export { default as Restore } from './Restore/Restore'
export { default as Products } from './Products/Products'
export { default as Main } from './Main/Main'
export { default as Profile } from './Profile/Profile'
export { default as ShoppingCart } from './ShoppingCart/ShoppingCart'
export { default as UserPage } from './UserPage/UserPage'
export { default as Favorite } from './Favorites/Favorites'

export type { IRegistrateFormInputs } from './Registration/interface'
export type { ILoginFormInputs } from './Authorization/interface'
export type { IForgotFormInputs } from './Forgot/interface'
export type { IRestoreFormInputs } from './Restore/interface'
export type { IProducts } from './Products/interface'
